### ISSUE TITLE
Should we be implementing the Page Object Design Pattern?

### ISSUE THREAD

**Issue by waryhermit** [ole-vi/BeLL-Apps#42]
You can read about it [here on the Selenium Wiki](http://www.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern). Seems like it would make tests more clear. We already are almost doing this with the `bell.py` file.

**Comment by aberdean** [comment]
@waryhermit Yes, I had that in mind when creating `bell.py`. The only problem is that I don't want to use an object oriented approach in `bell.py` to avoid double inheritance, since we also need to inherit BaseCase in our tests.

I thought `bell.py` was a good enough compromise. What do you think?

Of course, `bell.py` needs to be extended. I am writing new functions as I come across them (i.e., after finishing each test, I extrapolate from the test the functions that may need to be reused, and add them to `bell.py`).

If you have any better idea on how to achieve the same, please, feel free to share it and test it and, if it works, we can always improve on the `bell.py` idea (even scrap it to substitute it with something better!). 

Improvements are always welcome! ;-)

**Comment by waryhermit** [comment]
You can avoid double inheritance by separating the functionality of each page from its tests. The class for the page doesn't need to inherit `BaseCase` since it has no tests.

So each page of the bell app would be its own class, and the various tests can all use the page classes to navigate and click on things. Pretty much like this [short example on stackexchange](http://stackoverflow.com/questions/36601699/login-instance-in-the-setup-method-of-selenium).

I am not sure if the difference is clear or not, so I can write up a code example if its still not clear.

**Comment by sente** [comment]
At some point in the future we'll want to implement the Page Object pattern but at the moment I think it better to focus to simple, clean, tests.

**Comment by waryhermit** [comment]
@sente I think after we have more than a few tests the Page Object pattern will make our tests cleaner and simpler. If we plan to write more UI tests it would be worth implementing it now so we don't have to go back and refactor everything at a later date.

**Comment by waryhermit** [comment]
I have started using the Page Object pattern in CodeceptJS. I don't know how far I will take it. Since I started this as a discussion and I have decided to go forward with it, and this issue doesn't apply to a certain test in particular I think I will close it, unless anyone objects.
