### ISSUE TITLE
create python library for frequently used functions

### ISSUE THREAD

**Issue by aberdean** [ole-vi/BeLL-Apps#7]

**Comment by aberdean** [comment]
created login - Usage `bell.login(driver, name, password)`
created logout - Usage `bell.logout(driver)`

**Comment by aberdean** [comment]
created get_url (returns homepage url) - Usage `bell.get_url()`

**Comment by aberdean** [comment]
created goto - Usage `goto(driver, page)`

created add_member (returns (username, password) of new member or ("", "") if member already existing) - Usage `add_member(driver)` to add a random member, or `add_member(driver, first_name, last_name, middle_name, login, password, phone, email, language, birthdate, gender, level)`
Any of the parameters in add_member is optional, but if you want to skip one or more parameters, remember to add the parameter name to the parameters you're passing. For example, if you want to add a random female member, use `add_member(driver, gender="Female").
NOTE: The add_member function has not been tested yet, so someone should test it on the `7_bell_library` branch, before the branch can be merged.

created pick_string, pick_birthdate, pick_gender,  and pick_level - they can all be called without parameters. Ex.: `pick_string()`
The function pick_string() picks a random string of 5 lowercase letters.

**Comment by waryhermit** [comment]
@dogi I think we need to rethink how this issue applies to CodeceptJS. By implementing the page object pattern much more of the functionality will re-usable like this already. On the other hand, if you want to be able to do this kind of stuff by directly talking to couchdb I will have to write helpers.

@dogi Since this issue is for python mostly, do you think it would be better to close this and create specific issues for reusable functionality we want in Codeceptjs as we come across the need?

**Comment by dogi** [comment]
@waryhermit think you are spot on - I would even say that `page object pattern` was that what we want ;)
